### ISSUE TITLE
Functional tests improvements

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/securebanking-openbanking-uk-rcs#54]
## Story
As a developer of the Secure Access Banking Toolkit
I want to delete the objects created by the functional tests
so that I can be sure that the platform tested doesn't have a mix of live objects and objects created for test purposes.

> currently the clients (tpps) registered for test purposes are deleted, but it means that the consents created by these tpps are orfan and doesn't have a relation with any client, when a request is send to the platform to get any of these orfan consents the platform raise and error.

## Acceptance criteria
- When the functional tests runs against a platform, this tested platform doesn't have objects created by the tests.
   - [ ] The tpp's registered for tests have been deleted or unregistered.
   - [ ] The Consents created for tests have been deleted.
## Tasks
- [ ] Analyse the unit tests implemented and percentage of coverage.
- [ ] Implement the missing unit tests to increase the coverage.

### Release Notes

Affected App: securebanking-openbanking-uk-rcs
